name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  get-changed-folders:
    runs-on: ubuntu-latest
    steps:
      - name: get-changed-folders
        id: get_changed
        uses: Stockopedia/action-get-changed-files@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: false 
      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }}
            
